Pttb 235 admin can enable/disable all users but not itself.
proshore/TickerPRO-ProshoreTimeTrackingSystem-Backend pull request #113
Opened 2023-05-29 10:29 UTC by Sushant2055

1. Single action controller "UpdateUserStatus" used.
2. "Try-catch" functionality implemented.
3.  "Loggers" implemented from Exceptions.
4. Dependency injected for action class.
5. "Doc Blocks" implemented. 
6. "HttpResponse" trait implemented for uniform messages.
7. "Strict type" for id used.

2023-05-29 10:48 UTC, sahajmalla requested changes
Recheck the PR code. Tell your friends to do a PR once.

2023-05-29 10:48 UTC, sahajmalla commented on app/Http/Controllers/Actions/Admin/UpdateUserStatusAction.php
> +        try{
why this much catch???

2023-05-29 10:48 UTC, sahajmalla commented on app/Http/Controllers/AdminController.php
> +    private UserService $userService;
why private?

2023-05-31 07:26 UTC, Sushant2055 commented on app/Http/Controllers/Actions/Admin/UpdateUserStatusAction.php
> +        try{
1. used ModelNotFoundException->  when user is not found during findOrFail operation
2. used AuthorizationException-> So that an admin cannot disable itself  
3. used Query Exception->  UserStatus data is updated in database
4. used Exception-> to catch general exception
Is there need to remove any unwanted exceptions here

2023-05-31 07:27 UTC, Sushant2055 commented on app/Http/Controllers/AdminController.php
> +    private UserService $userService;
changed private into protected

2023-05-31 11:17 UTC, Amogh-svge commented on app/Http/Controllers/Actions/Admin/UpdateUserStatusAction.php
> +        }catch (AuthorizationException $authorizationException) {
QueryException and Authorization exception not needed

2023-05-31 11:24 UTC, Amogh-svge commented on app/Services/UserService.php
> +        if ($user->id === auth()->user()->id) {
dont throw exceptions from here it is not need

2023-05-31 11:24 UTC, Amogh-svge commented on app/Models/User.php
> +        public function getActiveAdminsCount(): int
not needed you are not using it

2023-05-31 11:25 UTC, Amogh-svge commented on app/Http/Controllers/AdminController.php
> +}
leave a space

2023-05-31 11:26 UTC, Amogh-svge commented on app/Http/Controllers/AdminController.php
> +     * @var UserService
write comment for parameter

2023-06-06 07:14 UTC, closed without merging