Pttb 271 validate reset password token
proshore/TickerPRO-ProshoreTimeTrackingSystem-Backend pull request #126
Opened 2023-06-06 09:12 UTC by piyushmhrzn

Check if the password reset token is valid and has not expired.

2023-06-07 03:27 UTC, sahajmalla requested changes

2023-06-07 03:27 UTC, sahajmalla commented on routes/api.php
> +    Route::get('verify-reset-token', VerifyPasswordTokenAction::class)->name('verify-reset-token');
route name is not acceptable it should be resourceful etc. Could you research it once?

2023-06-07 06:40 UTC, piyushmhrzn commented on routes/api.php
> +    Route::get('verify-reset-token', VerifyPasswordTokenAction::class)->name('verify-reset-token');
route name changed

2023-06-07 09:20 UTC, sahajmalla requested changes

2023-06-07 09:20 UTC, sahajmalla commented on app/Http/Requests/ValidateResetTokenRequest.php
> +            'token' => ['required', new VerfiyResetToken($this->email)],
Isn't token verification check done by laravel itself?

2023-06-08 04:53 UTC, sahajmalla approved these changes

2023-06-08 05:46 UTC, merged