PTTB-94 Project Section Pagination
proshore/TickerPRO-ProshoreTimeTrackingSystem-Backend pull request #58
Opened 2022-09-27 15:57 UTC by Rznjoc

2022-09-28 03:38 UTC, Prabeg29 commented on app/Http/Controllers/ProjectController.php
> +        $projects = Project::paginate();
@Rznjoc There might also be a limit sent from FE which you need to handle as well

2022-09-28 04:48 UTC, Rznjoc commented on app/Http/Controllers/ProjectController.php
> +        $projects = Project::paginate();
yes Limit is 50 and i've set it to 50.

2022-09-28 07:17 UTC, Prabeg29 approved these changes

2022-09-28 07:19 UTC, Prabeg29 requested changes

2022-09-28 07:19 UTC, Prabeg29 commented on app/Http/Controllers/ProjectController.php
>              'total' => count($projects),
@Rznjoc ok but now this won't work. Since you are already returning 50 projects, the count will return 50 as oppose to total count
Fix the count using aggregators

2022-09-28 17:36 UTC, closed without merging

2022-10-11 09:01 UTC, Rznjoc commented
yes Limit is 50 and i've set it to 50 (default 50 nai set gara vaneko cha
card ma)


On Wed, Sep 28, 2022 at 9:23 AM Prabeg Shakya ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In app/Http/Controllers/ProjectController.php
> <https://github.com/proshore/TickerPRO-ProshoreTimeTrackingSystem-Backend/pull/58#discussion_r981910451>
> :
>
> > @@ -91,7 +91,7 @@ public function updateBillableStatus(Request $request)
>
>      public function viewAllProjects()
>      {
> -        $projects = Project::all();
> +        $projects = Project::paginate();
>
> @Rznjoc <https://github.com/Rznjoc> There might also be a limit sent from
> FE which you need to handle as well
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/proshore/TickerPRO-ProshoreTimeTrackingSystem-Backend/pull/58#pullrequestreview-1122968377>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYDARSQJBK67VBRPHSC4TYDWAO4TXANCNFSM6AAAAAAQW5XU7Y>
> .
> You are receiving this because you were mentioned.Message ID:
> <proshore/TickerPRO-ProshoreTimeTrackingSystem-Backend/pull/58/review/1122968377
> @github.com>
>