Pttb 93 backend search filter not working
proshore/TickerPRO-ProshoreTimeTrackingSystem-Backend pull request #62
Opened 2022-10-12 05:01 UTC by Pranish97

2022-10-13 03:23 UTC, Prabeg29 commented
@Pranish97 If there are changes due to formatting, comment out where the actual change is

2022-10-13 04:33 UTC, Prabeg29 commented on app/Http/Controllers/ProjectController.php
> +        $projects = Project::latest()->paginate();
@Pranish97 Mention the change was made here..

2022-10-13 04:45 UTC, Pranish97 commented on app/Http/Controllers/ProjectController.php
> +        }
The card main changes were done between lines 106 to 108.

2022-10-13 04:45 UTC, Pranish97 commented on app/Http/Controllers/ProjectController.php
> +        $projects = Project::latest()->paginate();
As i was working on this card my next card was to show the latest add project to the top so I decided to finish another card too.

2022-10-13 04:53 UTC, Prabeg29 requested changes

2022-10-13 04:53 UTC, Prabeg29 commented on app/Http/Requests/ProjectRequest.php
> +            'project_name' => 'required |max:255||unique:projects',
@Pranish97 `||` ??

2022-10-13 05:07 UTC, Pranish97 commented on app/Http/Requests/ProjectRequest.php
> +            'project_name' => 'required |max:255||unique:projects',
As there won't be projects with the same name.

2022-10-14 05:42 UTC, Prabeg29 requested changes

2022-10-14 05:42 UTC, Prabeg29 commented on app/Http/Controllers/ProjectController.php
> +            $projects = Project::where('project_name', 'LIKE', "%" . $request['search'] . "%")->get();
@Pranish97 Do paginate here aswell

2022-10-14 07:33 UTC, Prabeg29 approved these changes

2022-10-14 07:33 UTC, merged