PTTB-180 Admin delete protected
proshore/TickerPRO-ProshoreTimeTrackingSystem-Backend pull request #67
Opened 2022-10-18 08:23 UTC by Rznjoc

2022-10-18 08:35 UTC, Prabeg29 requested changes

2022-10-18 08:35 UTC, Prabeg29 commented on app/Http/Requests/UserStoreRequest.php
> +            'password' => ['required','min:6','regex:/^.*(?=.{3,})(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[\d\x])(?=.*[!@#$%^&*]).*$/','confirmed'],
@Rznjoc Why not use the simple `Password` rule Laravel provides than to use this complex regex

2022-10-18 08:35 UTC, Prabeg29 commented on app/Http/Controllers/AdminController.php
> +        return response()->json([
@Rznjoc multiple return statements in the same block?

2022-10-18 08:35 UTC, Prabeg29 commented on routes/api.php
> -            Route::delete('{id}', 'deleteProject');
@Rznjoc Why is this route deleted? There is still functionality in FE to delete project

2022-10-18 08:35 UTC, Prabeg29 commented on app/Services/AdminService.php
> +    public static function deleteUser($id)
@Rznjoc This action according to naming does not match the functionality

2022-10-18 08:46 UTC, Rznjoc commented on app/Http/Requests/UserStoreRequest.php
> +            'password' => ['required','min:6','regex:/^.*(?=.{3,})(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[\d\x])(?=.*[!@#$%^&*]).*$/','confirmed'],
As FE has used Regex so this is done

2022-10-18 08:56 UTC, Rznjoc reviewed
deleteProject route added

2022-10-18 11:39 UTC, Prabeg29 commented on app/Http/Requests/UserStoreRequest.php
> +            'password' => ['required','min:6','regex:/^.*(?=.{3,})(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[\d\x])(?=.*[!@#$%^&*]).*$/','confirmed'],
@Rznjoc Brother check the Password rules and compare them with this. If you a real OG and prefer it the way it is, fine.

2022-10-20 16:35 UTC, Rznjoc commented on app/Http/Controllers/AdminController.php
> +        return response()->json([
done

2022-10-20 16:35 UTC, Rznjoc commented on app/Services/AdminService.php
> +    public static function deleteUser($id)
is it not OK for now?

2022-10-20 16:36 UTC, Rznjoc commented on app/Http/Requests/UserStoreRequest.php
> +            'password' => ['required','min:6','regex:/^.*(?=.{3,})(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[\d\x])(?=.*[!@#$%^&*]).*$/','confirmed'],
FE said this will be fine for now brother.

2022-10-21 07:51 UTC, Rznjoc reviewed
Final Changes

2022-11-07 05:00 UTC, sakaruk requested changes

2022-11-07 05:00 UTC, sakaruk commented on app/Services/UserService.php
> -    public static function checkUserIdExists($id)
Merge With the master and check if the function is used in other places too. I see that timelog controller uses it currently. Before removing function please check the dependencies

2022-11-08 14:55 UTC, Rznjoc commented on app/Services/UserService.php
> -    public static function checkUserIdExists($id)
Okay dai i will keep this in mind :)

2022-11-09 04:47 UTC, sakaruk requested changes

2022-11-09 04:47 UTC, sakaruk commented on app/Services/AdminService.php
> +    public static function checkUserIdExists($id)
Isn't this the same function that is in UserService ? Is it something different ?

2022-11-09 13:30 UTC, sakaruk approved these changes

2022-11-09 13:57 UTC, Rznjoc commented on app/Services/AdminService.php
> +    public static function deleteUser($id)
Function name changed to 'checkUserIdExists' which is already a used function in this project.

2022-11-09 15:25 UTC, Prabeg29 approved these changes

2022-11-09 15:25 UTC, merged