Client number accepts 10 digit mobile number
proshore/TickerPRO-ProshoreTimeTrackingSystem-Backend pull request #77
Opened 2023-05-08 07:09 UTC by piyushmhrzn

2023-05-09 08:11 UTC, sahajmalla requested changes

2023-05-09 08:11 UTC, sahajmalla commented on app/Http/Requests/ClientRequest.php
> +    public function messages()
I don't see the point of using the messages. Same message will be shown by laravel itself

2023-05-09 08:11 UTC, sahajmalla commented on app/Http/Requests/ClientRequest.php
> +            'client_number' => 'required|numeric|digits:10|regex:/^\d{10}$/',
Add comments on what Regex is doing. This will be beneficial for future understanding.

2023-05-09 08:43 UTC, piyushmhrzn commented on app/Http/Requests/ClientRequest.php
> +    public function messages()
It was just to add custom message like "It should be a valid mobile number".

2023-05-09 12:55 UTC, sahajmalla requested changes

2023-05-09 12:55 UTC, sahajmalla commented on app/Http/Requests/ClientRequest.php
> +            'client_number' => 'required|numeric|digits:10|regex:/^\d{10}$/',
numeric and digits:10 already satisfies the regex. You can remove it and check.

2023-05-09 17:16 UTC, piyushmhrzn commented on app/Http/Requests/ClientRequest.php
> +            'client_number' => 'required|numeric|digits:10|regex:/^\d{10}$/',
done. regex not needed as numeric and digits:10 satisfies the condition

2023-05-10 03:01 UTC, sahajmalla approved these changes

2023-05-10 06:17 UTC, merged