PTTB-233 role already assigned message is displayed
proshore/TickerPRO-ProshoreTimeTrackingSystem-Backend pull request #79
Opened 2023-05-08 07:39 UTC by Amogh-svge

What happened :
Even though a user has been assigned a role, the same role can still be assigned to that same user by the admin.

What should happen :
User should not be assigned same role twice. A message should be displayed which says that Role has been assigned to the user

2023-05-08 08:59 UTC, Amogh-svge commented
test comment

2023-05-08 14:36 UTC, sahajmalla requested changes

2023-05-08 16:18 UTC, Amogh-svge commented on app/Http/Controllers/AdminController.php
>          $rules = [
@sahajmalla resolved

2023-05-09 03:40 UTC, sahajmalla requested changes

2023-05-09 03:40 UTC, sahajmalla commented on app/Http/Controllers/AdminController.php
> +    private $userService;
Type hint this variable as UserService

2023-05-09 03:40 UTC, sahajmalla commented on app/Http/Requests/AssignRoleRequest.php
> +            'role_id' => 'required |integer'
Check if role id exists or not here

2023-05-09 03:40 UTC, sahajmalla commented on app/Http/Requests/AssignRoleRequest.php
> +            'email.exists' => "The email does not exists",
I don't see the point of adding messages that laravel already provides.

2023-05-09 03:40 UTC, sahajmalla commented on app/Services/UserService.php
> +    public static function getUser($cred)
Why static? Is this legacy code?

2023-05-09 03:40 UTC, sahajmalla commented on app/Services/UserService.php
> +    public static function getUser($cred)
Make the function name what it is doing. For instance, I don't think you are passing credentials here to get the users.

2023-05-09 03:40 UTC, sahajmalla commented on app/Services/UserService.php
> +        if ($existingRoles->contains($cred['role_id'])) {
You can do this in Request class.

2023-05-09 03:40 UTC, sahajmalla commented on app/Http/Controllers/AdminController.php
>              $role = UserRole::create([
do creation in service class too. Controllers should never be bulky

2023-05-09 11:13 UTC, Amogh-svge commented on app/Http/Controllers/AdminController.php
> +    private $userService;
resolved

2023-05-09 11:13 UTC, Amogh-svge commented on app/Http/Requests/AssignRoleRequest.php
> +            'role_id' => 'required |integer'
resolved

2023-05-09 11:13 UTC, Amogh-svge commented on app/Http/Requests/AssignRoleRequest.php
> +            'email.exists' => "The email does not exists",
removed

2023-05-09 11:13 UTC, Amogh-svge commented on app/Services/UserService.php
> +    public static function getUser($cred)
resolved

2023-05-09 11:14 UTC, Amogh-svge commented on app/Services/UserService.php
> +    public static function getUser($cred)
i have left getUser() function as it is because it is still being used by another function instead I have added a seperate function called assignUserRole()

2023-05-09 11:15 UTC, Amogh-svge commented on app/Services/UserService.php
> +        if ($existingRoles->contains($cred['role_id'])) {
resolved

2023-05-09 11:15 UTC, Amogh-svge commented on app/Http/Controllers/AdminController.php
>              $role = UserRole::create([
resolved

2023-05-09 13:06 UTC, sahajmalla requested changes

2023-05-09 13:06 UTC, sahajmalla commented on app/Http/Requests/AssignRoleRequest.php
> +    public function withValidator($validator)
Add a custom rule for this.  Making the custom rule will make your code more modular and reusable.

2023-05-09 15:20 UTC, Amogh-svge commented on app/Http/Requests/AssignRoleRequest.php
> +    public function withValidator($validator)
resolved

2023-05-09 15:21 UTC, Amogh-svge commented on app/Services/UserService.php
> +        $user = User::where('email', $cred['email'])->first();
resolved

2023-05-09 17:19 UTC, sahajmalla requested changes

2023-05-09 17:19 UTC, sahajmalla commented on app/Services/UserService.php
> +        $user = $this->userModel->getByEmail($cred['email'])->first();
use try catch

2023-05-09 17:19 UTC, sahajmalla commented on app/Services/UserService.php
> +        $role = UserRole::create([
You can inject the dependency of UserRole model too.

2023-05-10 11:24 UTC, Amogh-svge commented on app/Models/User.php
> +    public function scopeGetByEmail($query, $email)
resolved

2023-05-10 11:24 UTC, Amogh-svge commented on app/Rules/AssignedRoleRule.php
> +class AssignedRoleRule implements Rule
resolved

2023-05-10 11:25 UTC, Amogh-svge commented on app/Services/UserService.php
> +        $user = $this->userModel->getByEmail($cred['email'])->first();
resolved

2023-05-10 12:29 UTC, sahajmalla requested changes

2023-05-10 12:29 UTC, sahajmalla commented on app/Http/Controllers/AdminController.php
> +            $result = [
Add logger

2023-05-10 12:29 UTC, sahajmalla commented on app/Http/Controllers/AdminController.php
>              $result = [
Add Logger

2023-05-10 12:29 UTC, sahajmalla commented on app/Rules/CheckUserRoleExistsRule.php
> +    protected $email, $roleId;
add types

2023-05-10 12:29 UTC, sahajmalla commented on app/Rules/CheckUserRoleExistsRule.php
> +        $user = User::getByEmail($this->email)->first();
try catch

2023-05-10 12:29 UTC, sahajmalla commented on app/Models/User.php
> +    public function scopeGetByEmail(Builder $query, string $email)
better name would be scopeEmail

2023-05-10 12:29 UTC, sahajmalla commented on app/Services/UserService.php
> +        $user = $this->userModel->getByEmail($cred['email'])->firstOrFail();
try catch in every db actions

2023-05-10 12:29 UTC, sahajmalla commented on database/migrations/2022_03_24_111817_create_user_roles_table.php
> +            $table->unique(['user_id', 'role_id']);
Add foreign keys

2023-05-10 12:38 UTC, Amogh-svge commented on app/Models/User.php
> +    public function scopeGetByEmail(Builder $query, string $email)
its easy to understand

2023-05-11 04:54 UTC, Amogh-svge commented on database/migrations/2022_03_24_111817_create_user_roles_table.php
> +            $table->unique(['user_id', 'role_id']);
another migration is present to which alters the table and adds foreign key to this .

2023-05-11 07:22 UTC, sahajmalla requested changes

2023-05-11 07:22 UTC, sahajmalla commented on app/Http/Controllers/AdminController.php
> +    public function __construct(UserService $userService)
add comments

2023-05-11 07:22 UTC, sahajmalla commented on app/Rules/CheckUserRoleExistsRule.php
> +    protected string|null $email;
why null?

2023-05-11 07:22 UTC, sahajmalla commented on app/Services/UserService.php
> +        $user = $this->userModel->getByEmail($cred['email'])->first();
try catch is not done here

2023-05-11 07:22 UTC, sahajmalla commented on app/Services/UserService.php
> +        $user = $this->userModel->getByEmail($cred['email'])->first();
Always use laravel "Arr" helper function when taking actions from array rather than taking associative array as it has lots of side effects.

2023-05-11 07:22 UTC, sahajmalla commented on app/Services/UserService.php
> +            'role_id' => $cred['role_id']
$user->role()->create()

2023-05-11 07:22 UTC, sahajmalla commented on database/migrations/2022_03_24_111817_create_user_roles_table.php
> +            $table->unique(['user_id', 'role_id']);
Then why are you updating this migration? Always create new migration if you want to update some rows.

2023-05-11 07:22 UTC, sahajmalla commented on routes/api.php
> +            Route::controller(ProjectController::class)->prefix('project')->group(function () {
why are you doing this? Route::patch mai garna milthyo hola

2023-05-11 07:26 UTC, Amogh-svge commented on routes/api.php
> +            Route::controller(ProjectController::class)->prefix('project')->group(function () {
not my code yo part maile hereko chaina

2023-05-11 07:32 UTC, Amogh-svge commented on app/Services/UserService.php
> +        $user = $this->userModel->getByEmail($cred['email'])->first();
yo ta purano code ho

2023-05-11 12:56 UTC, Amogh-svge commented on app/Rules/CheckUserRoleExistsRule.php
> +    protected string|null $email;
i made it null because without null in case of email not being provided instead of showing email is required message it shows an error, I will be sending you a screenshot of it in slack

**_"App\\Rules\\CheckUserRoleExistsRule::__construct(): Argument #1 ($email) must be of type string, null given, called in /var/www/html/TimeTrackerMain/app/Http/Requests/AssignRoleRequest.php on line 36"_**

2023-05-11 13:28 UTC, Amogh-svge commented on app/Services/UserService.php
> +            'role_id' => $cred['role_id']
i dont think we can use create like above to insert data in pivot table instead we can use attach but it does not inserts datetime

2023-05-11 14:07 UTC, Amogh-svge commented on app/Services/UserService.php
> +        $user = $this->userModel->getByEmail($cred['email'])->first();
resolved

2023-05-15 05:35 UTC, sahajmalla requested changes

2023-05-15 05:35 UTC, sahajmalla commented on app/Traits/HttpResponses.php
> +    public function successResponse($data, string $message = null, int $code = Response::HTTP_OK): JsonResponse
add type for $data

2023-05-15 05:35 UTC, sahajmalla commented on app/Traits/HttpResponses.php
> +    public function errorResponse($data, string $message = null, int $code = Response::HTTP_INTERNAL_SERVER_ERROR): JsonResponse
Add type for $data

2023-05-15 05:50 UTC, Amogh-svge commented on app/Traits/HttpResponses.php
> +    public function errorResponse($data, string $message = null, int $code = Response::HTTP_INTERNAL_SERVER_ERROR): JsonResponse
resolved

2023-05-15 05:59 UTC, sahajmalla approved these changes

2023-05-15 07:13 UTC, closed without merging

2023-05-15 07:14 UTC, 1Aayush3 commented
Merge into dev branch first