added projects column to clients list
proshore/TickerPRO-ProshoreTimeTrackingSystem-Backend pull request #80
Opened 2023-05-08 08:54 UTC by smellycat5

2023-05-09 05:53 UTC, sahajmalla requested changes

2023-05-09 05:53 UTC, sahajmalla commented on app/Http/Controllers/ClientController.php
> +        $projects = Client::with('projects')->get();
Always return paginated instance, rather than all

2023-05-09 05:53 UTC, sahajmalla commented on app/Http/Requests/ClientRequest.php
> +            'client_number' => 'required|integer|regex:/^\d{10}$/',
Add comments about what this regex is doing. Its better for future use.

2023-05-09 05:53 UTC, sahajmalla commented on app/Http/Controllers/ClientController.php
> +        $projects = Client::with('projects')->get();
Do this in service class

2023-05-09 05:53 UTC, sahajmalla commented on composer.lock
Looks like composer has been updated. Ensure that all team has the same version.

2023-05-10 02:57 UTC, sahajmalla requested changes

2023-05-10 02:57 UTC, sahajmalla commented on app/Http/Requests/ClientRequest.php
> +            'client_number' => 'required|numeric|digits:10|regex:/^\d{10}$/', // makes sure the number is exactly 10 digits
numeric, digits:10 already satisfies the regex. Remove the regex and check

2023-05-10 02:57 UTC, sahajmalla commented on app/Http/Requests/ClientRequest.php
> +            'client_name' => 'required|regex:/^[\pL\s\-]+$/u|max:255', //makes sure there are no numbers in the name and doesn't allow more than one space
No numbers in the string are acceptable but what if the client has a middle name? It should allow more than one space.

2023-05-10 02:57 UTC, sahajmalla commented on app/Models/Client.php
> +    protected $perpage = 20;
Type hint this as int

2023-05-10 08:59 UTC, smellycat5 commented on app/Models/Client.php
> +    protected $perpage = 20;
im not sure how to type hint

2023-05-11 07:26 UTC, sahajmalla requested changes

2023-05-12 06:19 UTC, smellycat5 commented on app/Http/Controllers/ProjectController.php
>      public function __construct(protected ProjectService $projectService)
Resolved

2023-05-12 06:20 UTC, smellycat5 commented on app/Http/Requests/ClientRequest.php
> +            'client_name' => 'required|regex:^[A-Za-z]+(?:\s[A-Za-z]+)+$|max:255', //makes sure the name only accepts aplabetic characters.
client name only takes alphabets so regex is used

2023-05-12 06:24 UTC, sahajmalla approved these changes

2023-05-15 14:58 UTC, merged