Pttb 247 backend edit client
proshore/TickerPRO-ProshoreTimeTrackingSystem-Backend pull request #81
Opened 2023-05-10 11:10 UTC by smellycat5

Added Edit client function

2023-05-10 11:29 UTC, Amogh-svge commented on app/Http/Controllers/ClientController.php
> +    public function EditClient(EditClientRequest $request, $id)
add comments

2023-05-10 11:29 UTC, Amogh-svge commented on app/Services/ClientService.php
> +    public static function editClient(array $validatatedEditClient, $id)
add comments

2023-05-10 11:43 UTC, Amogh-svge commented on app/Http/Controllers/ClientController.php
>          $result = ClientService::addClient($validatedAddClient);
inject clientService dependency in constructor

2023-05-10 11:44 UTC, Amogh-svge commented on app/Http/Controllers/ClientController.php
>          $result = ClientService::addClient($validatedAddClient);
inject clientService dependency in constructor

2023-05-10 12:22 UTC, sahajmalla requested changes

2023-05-10 12:22 UTC, sahajmalla commented on app/Http/Controllers/ClientController.php
> +        $clients = Client::all();
try catch

2023-05-10 12:22 UTC, sahajmalla commented on app/Http/Controllers/ClientController.php
> +            $result = ClientService::EditCLient($validatedEditClient, $id);
use by dependency injection

2023-05-10 12:22 UTC, sahajmalla commented on app/Services/ClientService.php
> +        $client = Client::where('id', $id)->firstorfail();
try catch

2023-05-10 12:22 UTC, sahajmalla commented on routes/api.php
> +            Route::patch('/{id}', 'editClient');
try using resourceful routes

2023-05-10 12:22 UTC, sahajmalla commented on app/Exceptions/Handler.php
> +    public function render($request, Throwable $exception)
what are you trying to do here?

2023-05-10 12:22 UTC, sahajmalla commented on app/Http/Controllers/ClientController.php
> +    public function EditClient(EditClientRequest $request, $id)
Rename the function to resourceful funtion i.e. show, index, update, destroy etc

2023-05-15 07:58 UTC, sahajmalla requested changes

2023-05-15 07:58 UTC, sahajmalla commented on app/Exceptions/Handler.php
> +        if ($exception instanceof ModelNotFoundException) {
remove this

2023-05-15 07:58 UTC, sahajmalla commented on app/Http/Controllers/ClientController.php
> +    public function __construct(Client $client, ClientService $clientService)
Why are you passing Client model?

2023-05-15 07:58 UTC, sahajmalla commented on app/Http/Requests/EditClientRequest.php
> +}
Add one space below

2023-05-15 07:58 UTC, sahajmalla commented on app/Models/Client.php
> +    protected int $perpage = 50;
why per page 50? that is too much

2023-05-15 07:58 UTC, sahajmalla commented on routes/api.php
> +            Route::get('/', 'index');
use route resource and add except show, destroy

2023-05-16 03:38 UTC, sahajmalla requested changes

2023-05-16 03:38 UTC, sahajmalla commented on app/Exceptions/Handler.php
> +use Illuminate\Database\Eloquent\ModelNotFoundException;
remove unused imports

2023-05-16 03:38 UTC, sahajmalla commented on app/Http/Controllers/ClientController.php
> +    public function __construct(Client $client, ClientService $clientService)
Where have you used? I don't see any

2023-05-16 03:38 UTC, sahajmalla commented on app/Http/Controllers/ClientController.php
> +            return response()->json([
Use the response trait  everywhere that was created by @Amogh-svge

2023-05-16 03:38 UTC, sahajmalla commented on app/Http/Controllers/ClientController.php
> +                'message' => $exception->getMessage(),
Dont give exception message to the user. Add message i.e. Something went wrong or that is meaningful. Also log the exception message.

2023-05-16 03:38 UTC, sahajmalla commented on app/Http/Controllers/ClientController.php
> +        } catch (Exception $exception) {
Try to catch what service is throwing. Eg: model not found exception here.

2023-05-16 03:38 UTC, sahajmalla commented on app/Http/Controllers/ClientController.php
> +            $result =  $this->clientService->EditCLient($validatedEditClient, $id); ////// use dependency
use camel case. Why EditCLient?

2023-05-16 05:49 UTC, smellycat5 commented on app/Http/Controllers/ClientController.php
> +    public function __construct(Client $client, ClientService $clientService)
line number 37

2023-05-16 10:22 UTC, sahajmalla requested changes

2023-05-16 10:22 UTC, sahajmalla commented on app/Http/Controllers/ClientController.php
> +            return $this->errorResponse([],'No Clients to display',Response::HTTP_BAD_REQUEST);
Change the response code to not found not bad request

2023-05-19 06:29 UTC, sahajmalla requested changes

2023-05-19 06:29 UTC, sahajmalla commented on app/Http/Controllers/ClientController.php
> +            return $this->errorResponse([], 'Query Exception', Response::HTTP_BAD_REQUEST);
Give message i.e. could not add client as something is wrong with the query. Give proper message update other query exception message too.

2023-05-19 06:29 UTC, sahajmalla commented on app/Http/Controllers/ClientController.php
> +        } catch (ModelnotFoundException $modelNotFoundException) {
Check the name of exception this is mistake

2023-05-19 06:29 UTC, sahajmalla commented on app/Services/ClientService.php
> +            Client::create($validatedAddClient);
At some place you are using $clients. At some you are using model. Make it consistent

2023-05-22 09:42 UTC, 1Aayush3 approved these changes

2023-05-22 10:11 UTC, merged