Pttb 84 backend delete client
proshore/TickerPRO-ProshoreTimeTrackingSystem-Backend pull request #84
Opened 2023-05-15 06:26 UTC by smellycat5

added delete client function

2023-05-15 08:30 UTC, Amogh-svge commented on app/Http/Controllers/ClientController.php
> +            $result =  $this->clientService->EditCLient($validatedEditClient, $id); ////// use dependency
method ko name farak cha should be editClient

2023-05-24 10:44 UTC, sahajmalla requested changes

2023-05-24 10:51 UTC, smellycat5 commented on app/Http/Controllers/ClientController.php
> +    public function destroy($client): JsonResponse
cannot handle type errors in controller so removed type hinting in controller
type hinted in Service class instead

2023-05-26 07:44 UTC, sahajmalla approved these changes

2023-05-27 05:33 UTC, merged