refactoring code
proshore/TickerPRO-ProshoreTimeTrackingSystem-Backend pull request #87
Opened 2023-05-15 08:39 UTC by piyushmhrzn

2023-05-17 10:28 UTC, sahajmalla requested changes
If the controller has other than these resourceful functions, use actions class.

2023-05-19 06:11 UTC, piyushmhrzn commented
Used single action controllers for forgot password and reset password actions

2023-05-23 05:06 UTC, sahajmalla requested changes
Do all validation in form request class

2023-05-23 05:06 UTC, sahajmalla commented on app/Services/UserService.php
> +    public function checkOldPass(array $validatedResetPass): bool
do this in form request class

2023-05-23 09:36 UTC, piyushmhrzn commented on app/Http/Controllers/Actions/Auth/ResetPasswordAction.php
> +            if (!$checkOldPass){
ok

2023-05-23 09:42 UTC, piyushmhrzn commented on app/Services/UserService.php
> +    public function checkOldPass(array $validatedResetPass): bool
ok

2023-05-24 10:43 UTC, sahajmalla requested changes

2023-05-24 10:43 UTC, sahajmalla commented on app/Http/Requests/ForgotPasswordRequest.php
> +            'email.exists' => 'User with the given email address not found'
is this necessary?

2023-05-24 10:43 UTC, sahajmalla commented on app/Http/Requests/PasswordResetRequest.php
> +        return [
is this necessary?

2023-05-24 14:57 UTC, piyushmhrzn commented on app/Http/Requests/PasswordResetRequest.php
> +        return [
Laravel Default Message was "The selected email is invalid."
So, I used custom message "User with the given email address not found" for more specific message.
Is this specific message justified here?

2023-05-25 05:46 UTC, sahajmalla commented on app/Http/Requests/PasswordResetRequest.php
> +        return [
yes that is justified.

2023-05-25 05:49 UTC, sahajmalla requested changes

2023-05-25 05:49 UTC, sahajmalla commented on app/Http/Controllers/Actions/Auth/ForgotPasswordAction.php
> +        } catch (QueryException $queryException) {
why are you catching query exception here?

2023-05-25 05:49 UTC, sahajmalla commented on app/Http/Controllers/Actions/Auth/ResetPasswordAction.php
> +        }  catch (QueryException $queryException) {
why are you catching query exception?

2023-05-25 05:57 UTC, piyushmhrzn commented on app/Http/Controllers/Actions/Auth/ForgotPasswordAction.php
> +        } catch (QueryException $queryException) {
Is it already handled by forgot password request when we use exists for email?

2023-05-26 06:11 UTC, sahajmalla approved these changes

2023-05-26 06:31 UTC, merged