Pttb 290 token should be shown in response
proshore/TickerPRO-ProshoreTimeTrackingSystem-Backend pull request #94
Opened 2023-05-19 09:36 UTC by Amogh-svge

reponse should contain token only in local and development server it should not contain token in production serve

2023-05-19 09:52 UTC, smellycat5 commented on app/Http/Controllers/Actions/Invite/InviteOthersAction.php
> +
why is there extra space here. plseae remove this

2023-05-19 09:52 UTC, smellycat5 commented on app/Http/Controllers/Actions/Invite/InviteOthersAction.php
> +
remove extra space here

2023-05-19 09:52 UTC, smellycat5 commented on app/Http/Controllers/AdminController.php
unnecssary blank space

2023-05-19 09:53 UTC, smellycat5 commented on app/Services/InviteService.php
> +
same here remove it lol

2023-05-19 09:53 UTC, smellycat5 commented on app/Services/InviteService.php
> +
same here

2023-05-19 09:54 UTC, smellycat5 reviewed
remove extra spaces

2023-05-19 10:05 UTC, Amogh-svge commented on app/Http/Controllers/Actions/Invite/InviteOthersAction.php
> +     * @param  \Illuminate\Http\Request  $request
ahh solved

2023-05-23 05:09 UTC, sahajmalla requested changes
Why should not response content token in the production env and only in the local and dev servers?

2023-05-29 06:55 UTC, closed without merging